CREATE TABLE LOGOS_EMPRESA(
LEM_CODIGO BIGINT IDENTITY(1,1) NOT NULL,
LEM_RUTA NVARCHAR(250),
LEM_TIPO NVARCHAR(250))


CREATE PROCEDURE RutasLogo
@tipo nvarchar(250)
AS
SELECT LEM_RUTA FROM LOGOS_EMPRESA WHERE LEM_TIPO = @tipo
GO
